### ISSUE TITLE
docker.Makefile no longer works on Windows

### ISSUE THREAD

**Issue by garethr** [docker/app#200]
A few unixisms have crept in which mean this no longer works on Windows. Specifically:

* The BUILDTIME option relies on sed and time, which are likely not present. Best to either warn rather than error, or to replace with relevant Windows standard utilities
* The addition of /dev/null to the git shell commands causes them to fail, as per the snippet below. Note this worked with the previous version.

```
make -f docker.Makefile cross
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
docker build --target= -t docker-app-cross --build-arg COMMIT= --build-arg TAG= --build-arg BUILDTIME= .
```

**Comment by vdemeester** [comment]
Should have been fixed by https://github.com/docker/app/pull/225 so I'll close it for now :angel:
