### ISSUE TITLE
Generating Helm charts not dependent on the Compose Kubernetes controller

### ISSUE THREAD

**Issue by kinghuang** [docker/app#239]
**Description**

Is there any possibility that docker-app will be able to generate Helm charts that are not dependent on the Compose Kubernetes controller available in Docker for Mac/Windows and Docker EE? Or, will the Helm support always rely on that?

**Steps to reproduce the issue:**

1. Generate a Helm chart using `docker-app helm`.
2. Attempt to install the chart outside of Docker for Mac/Windows or Docker EE.

**Describe the results you received:**

The resource version/type cannot be resolved.

**Describe the results you expected:**

The Helm chart is installed.

**Additional information you deem important (e.g. issue happens only occasionally):**

This limitation is noted in the README file.

*Note that this requires the Compose Kubernetes controller available in Docker for Windows and Docker for Mac, and in Docker Enterprise Edition.*

**Output of `docker version`:**

```
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:12:05 2018
 OS/Arch:      darwin/amd64
 Experimental: true
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.10.1
  Git commit:   f150324
  Built:        Wed May  9 22:20:16 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

**Output of `docker-app version`:**

```
Version:      v0.2.0
Git commit:   854872f
Build time:   2018-06-11T15:06:17.093522032+00:00
OS/Arch:      darwin/amd64
Experimental: off
Renderers:    none
```

**Output of `docker info`:**

```
Containers: 54
 Running: 22
 Paused: 0
 Stopped: 32
Images: 154
Server Version: 18.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: w97q3z0azzcv970g3e5hn9ski
 Is Manager: true
 ClusterID: o1cdcrn2etmq3kcz2aapse3n4
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.65.3
 Manager Addresses:
  192.168.65.3:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.786GiB
Name: linuxkit-025000000001
ID: OQ6Q:SF73:CGCW:XMZS:FHR4:BXKW:2EG3:KWGE:2EAK:OCTQ:2OWJ:LWCO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 140
 Goroutines: 332
 System Time: 2018-06-19T21:01:05.7712531Z
 EventsListeners: 10
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by garethr** [comment]
Hi @kinghuang. At the moment as you've spotted much of the functionality for Compose on Kubernetes is in the controller, and that's currently only available in Docker Desktop and Docker EE. The controller has a bunch of advantages, including giving us first-class `Stacks` in the Kubernetes API for other tools to use. It's possible that the controller availability might change in the future but not for the moment. If that stays we may implement something purely client side as well but while we're at an early experimental stage with `docker-app` that's not a priority I'm afraid.
