### ISSUE TITLE
CI is too complex

### ISSUE THREAD

**Issue by silvin-lubecki** [docker/app#262]
There are several parts involved, and it's really hard to backtrack what is called, when and where by the CI. In the list we have 2 jenkin files, 2 Makefiles (one called by jenkins, the other in a container or by the Dockerfile).
I think it will be really hard for an external contributor to understand why the CI failed on her/his PR and to try to reproduce the problem locally.

**Comment by vdemeester** [comment]
The 2 CIs is temporary (i.e. it will soon be the only one `jenkins.dockerproject.org`)

**Comment by silvin-lubecki** [comment]
I know it's not the best time now with these 2 CIs, but I don't think it's the main issue. My concern is more on the path `docker.Makefile` -> `Dockerfile` -> `Makefile` which is quite disturbing. I mean, we are talking about a "simple" golang binary with some e2e tests. We are far away from the `docker cli` complexity... but still the flow is over-complex... I don't have a silver bullet to fix this, but I think we really need to focus on this, and keep it in mind if we want to involve the community.

Maybe Make is not the right tool to do what we are trying to do? @mat007 mentioned https://github.com/dnephin/dobi, is it worth giving a try?

**Comment by garethr** [comment]
I think the documentation nicely covers what the majority of contributors would want to do, and why we have two separate entry points: https://github.com/docker/app/blob/master/BUILDING.md.

Introducing some other tool than `make` would probably still mean two paths as well I think.

**Comment by mat007** [comment]
> Introducing some other tool than make would probably still mean two paths as well I think.

Not necessarily, this is an idea I've been toying with for a little while now: https://docs.google.com/document/d/1---pUZhEC7Fffbg37dg6JZ08SedzkaPLfS9zyegdIyE/edit#
Still sketchy but I will likely prototype it at some point.

**Comment by thaJeztah** [comment]
https://github.com/dnephin/dobi

**Comment by ijc** [comment]
As Gareth says, `BUILDING.md` covers this and given the amount of time which has passed since this was raised and the issues involved it doesn't seem like this is something we are going to change so I'm closing this issue.
