### ISSUE TITLE
No Windows support for application packages as images

### ISSUE THREAD

**Issue by chris-crone** [docker/app#264]
**Description**

As one cannot create a `FROM scratch` image for Windows containers; one cannot create or pull application packages from the Hub.

**Steps to reproduce the issue:**
1. Enable Windows containers on Docker Desktop
1. `docker-app save`

**Describe the results you received:**

Error, unable to create `FROM scratch` image.

**Describe the results you expected:**

`docker-app` saves the application package as an image.

cc @sixeyed

**Comment by chris-crone** [comment]
The first step is to document this limitation while we work out the way forward.

**Comment by mnottale** [comment]
This is now fixed in master as we now bake our own images and talk directly to the registry.
