### ISSUE TITLE
docker-app init: validate compose file

### ISSUE THREAD

**Issue by guillaumerose** [docker/app#281]
Currently, the compose file is just copied as it is. A validation of the compose file format here can help. Currently I'm running docker-app render to see if everything is correct.

**Comment by garethr** [comment]
We're currently doing some specification work around the format in https://github.com/docker/app/pull/269. That PR has some internal tools for validation which we're discussing exposing as `docker-app validate` as well.

I _think_ however that `init` may fail currently if it's not provided a valid Compose file? @mnottale

**Comment by garethr** [comment]
We now have a validate command in master from https://github.com/docker/app/pull/290, this will be in the next release.
