### ISSUE TITLE
Improve render unit test coverage

### ISSUE THREAD

**Issue by chris-crone** [docker/app#297]
**Description**

We currently only test for a missing variable in the [render unit test](https://github.com/docker/app/blob/master/internal/render/render_test.go). Add the following tests:
- missing piece of docker application package (settings, metadata, or docker-compose)
- invalid syntax
- invalid ordering of sections for single-file format

**Comment by vdemeester** [comment]
Speaking with #286 in mind

> invalid ordering of sections for single-file format

This is on `packager.Extract` to test (i.e. `render.Render` still loads files but it works on an *extracted* app — so no single-file format to handle).

> invalid syntax

renderers are already tested, and we can make the assumption (and we should) that the library we use (`docker/cli/cli/compose`) is well tested (i.e. we don't need to re-test).

**Comment by silvin-lubecki** [comment]
The `validate` command already do this job (at least part of it). Maybe we should always validate before every other commands? But then the `validate` command would become a little useless?

**Comment by chris-crone** [comment]
It looks like as part of the refactoring that we've done, we're now better unit testing render.
