### ISSUE TITLE
docker-app render fails to render shm_size as a property of the Compose file

### ISSUE THREAD

**Issue by jhrabi** [docker/app#304]
**Description**

docker-app render fails to render shm-size as a property of the Compose file

**Steps to reproduce the issue:**
1. Clone https://github.com/jhrabi/dockerapp-shm-size-demo
2. Run docker-app render helloworld.dockerapp from inside the project

**Describe the results you received:**
```
version: "3.5"
services:
  hello-world:
    image: hello-world
```

**Describe the results you expected:**
```
version: "3.5"
services:
  hello-world:
    image: hello-world
    shm_size: 2G
```

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:20:16 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:58 2018
  OS/Arch:      linux/amd64
  Experimental: false

```

**Output of `docker-app version`:**

```

Version:      v0.2.0
Git commit:   854872f
Build time:   2018-06-11T15:06:17.093522032+00:00
OS/Arch:      linux/amd64
Experimental: off
Renderers:    none

```

**Output of `docker info`:**

```
Containers: 49
 Running: 12
 Paused: 0
 Stopped: 37
Images: 1510
Server Version: 18.03.1-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.2.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.26GiB
Name: testserver
ID: 4UV7:LJWO:PRJP:PJWY:YEYA:5RLZ:23XJ:TDFB:3G4L:SST7:5RSJ:UBQU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: jhrabi
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):

Running on AWS

**Comment by vdemeester** [comment]
@jhrabi Thanks for the report. `docker/app` is based on the `docker/cli` composefile implementation, and thus only supports what `docker/cli` supports. `shm_size` is part of the field that are not supported.

That said, even though it's not supported, as it is in the `3.x` schema, it should be able to merge it. We need to fix that in `docker/cli`

**Comment by silvin-lubecki** [comment]
The `docker/cli` code: https://github.com/docker/cli/blob/master/cli/compose/types/types.go#L25

**Comment by jhrabi** [comment]
@vdemeester @silvin-lubecki Thanks for the quick response. Looks like if I wanted to, I could build docker-app myself with a modified types file until cli gets updated, so at least there's a workaround for now.

**Comment by jhrabi** [comment]
@vdemeester Should I make a request on docker/cli to have shm_size be removed from the unsupported list?

**Comment by vdemeester** [comment]
@jhrabi nah, they don't really need to be removed from the unsupported list I think (as the cli itself, when doing a `docker stack deploy` should still warn they are not supported), they just need to be in the struct so that they are correctly marshalled and unmarshalled by the library.

**Comment by jhrabi** [comment]
@vdemeester Thanks! 😀
