### ISSUE TITLE
customize the docker hub repo to push to

### ISSUE THREAD

**Issue by jgallen23** [docker/app#320]
I love the idea of dockerapps, but the one downside is it creates another private repo for every app we want to deploy (lots in our case).  It would be nice if we could push up to the same repo as our app and then have it tagged as dockerapp or dockerapp_latest and then I could pull that down and deploy.

so instead of `company/awesomeapp.dockerapp:latest` it would be `company/awesomeapp:dockerapp_latest`

Is this possible now?  If not, is this something you'd consider adding?

**Comment by chris-crone** [comment]
Hi @jgallen23!

Thanks for your feedback. It would be useful to add a flag to specify which repository the application is pushed to and that would fix your user case. I've added it to our backlog so that we can investigate doing it.

**Comment by drozzy** [comment]
Can we presently specify the registry? Or does it always push to docker hub?

**Comment by vdemeester** [comment]
@drozzy with `--namespace` you should be able to specify the registry you want:

```
$ docker-app push --namespace foo.bar:5000/vdemeester hello-word.dockerapp
```
