### ISSUE TITLE
Config files within dockerapp

### ISSUE THREAD

**Issue by jgallen23** [docker/app#336]
I'm porting over a docker-compose file to dockerapp and I have a local config, which works fine if I do `docker stack deploy`, but if I push up the dockerapp and I try to run `docker-app deploy [image]` it complains it can't find the config file.  Is there any way to reference the config file inside the image?

**Comment by vdemeester** [comment]
Hi @jgallen23, thanks for the issue, but I have some question about it. When you say `I have a local config`, what do you mean : client config (`~/.docker/config.json`), swarm mode config, … ?
Also, can you post the actual error you get when doing the `docker-app deploy` ?

**Comment by mikeparker** [comment]
Hi @jgallen23 I've implemented a way to attach additional files in the docker-app as part of https://github.com/docker/app/pull/392. Let me know if this solves your use case :)

**Comment by ijc** [comment]
Assuming #392 did solve this and closing. Please reopen if this isn't the case.
