### ISSUE TITLE
[Enhancement Request] Better error message when using docker-app render on dockerapp that hasn't been pulled yet.

### ISSUE THREAD

**Issue by jhrabi** [docker/app#337]
When running ` docker-app render` on a dockerapp that hasn't been pulled yet from a registry, we get the following error message:

Error response from daemon: reference does not exist

The dockerapp is then pulled if it exists in the registry, and the render occurs as expected. What I'd like to request is that docker-app clarifies what's happened and what's going to occur. (IE: "jhrabi/myapp.dockerapp was not found. Attempting to pull from registry) without stating the error from the daemon, or something that makes it a little more obvious why this message occured in the first place.

**Comment by ijc** [comment]
Thanks for the report.

I think this was solved somewhere along the way, `docker-app` now just DTRT without extraneous error messages:
```console
$ cd examples/wordpress
$ ../../bin/docker-app push --repo localhost:5000/wordpress.dockerapp --tag xyzzy wordpress 
sha256:ccae8e1651d8e0f510275a743f9931d616d5b6b676a6bf3f284af81aaad32f73
$ ../../bin/docker-app deploy localhost:5000/wordpress.dockerapp:xyzzy 
Creating network wordpress_overlay
Creating service wordpress_wordpress
Creating service wordpress_mysql
$ docker stack ls
NAME                SERVICES            ORCHESTRATOR
wordpress           2                   Swarm

```

Closing, please reopen if that's not right.

**Comment by jhrabi** [comment]
Looks good as of 0.6.0. Thanks
