### ISSUE TITLE
Development environment with dependencies

### ISSUE THREAD

**Issue by drozzy** [docker/app#338]
This is a great tool!

How would you handle a case where you want to work on a particular service in development while spinning up all the dependencies?

What I currently do, is have a special docker file `Dockerfile.dev` that builds only development environment and then mounts a host directory inside that docker container, _and_ I also have a `docker-compose-dev.yml` that brings up all the dependencies except the service I'm working on.

Will docker-app improve this flow? If so, how?

Thank you very much!

**Comment by garethr** [comment]
Hi @drozzy, thanks for the question. Do you have an example of this setup somewhere public? That would help us look at how this (or some other tooling) might help.

What do you see as the main drawbacks of your flow at the moment?

**Comment by drozzy** [comment]
For example, take any docker-compose app:

https://github.com/dockersamples/example-voting-app

How should one go about setting up the development environment?

You have two options:

1. Install all the dev tools and libraries onto the dev machine (including all dependencies like [redis](https://github.com/dockersamples/example-voting-app/blob/master/docker-compose.yml))
2. Bring up the app with docker-compose but then shut-down the app you're working on and run it with a src-directory mounted inside the container.

The first approach is very tedious, and what docker should save us from. The second approach is not documented anywhere.

Maybe this is not so much docker-app question, feel free to close it.

**Comment by ChristianKniep** [comment]
@drozzy Love docker/app myself and trying to wrap my head around the same question.

**Comment by jgallen23** [comment]
We have kept our docker-compose.yml in the root for development and the dockerapp folder is for stage/production deployments.  It makes it a little annoying to keep both in sync, but there are enough differences where it's better to keep them completely separate
