### ISSUE TITLE
What is the . in the placeholder variables?

### ISSUE THREAD

**Issue by drozzy** [docker/app#342]
Sorry for the stupid question, but when placeholders are defined like this:

`mysql.image.version`

What does it mean? How do you override/set them? 

I'm not familiar with Helm or maybe I missed a doc explanation..

I would be inclined to think that you do this:

```
docker-app --set mysql.image.version=1
```

But I'm sure that's wrong...

**Comment by silvin-lubecki** [comment]
Hello @drozzy, you will find more explanations also in the [examples](https://github.com/docker/app/tree/master/examples). Please check the [Wordpress](https://github.com/docker/app/tree/master/examples/wordpress) example. You will find a [compose file](https://github.com/docker/app/blob/master/examples/wordpress/wordpress.dockerapp/docker-compose.yml#L6) with some variables, like `${mysql.image.version}`.
The value of this variable is defined [here](https://github.com/docker/app/blob/master/examples/wordpress/wordpress.dockerapp/settings.yml#L4).
So you can define the default value of your variable in the `settings.yml` file, or override it when deploying or rendering your app, using the `--set` flag. So here for our example, we can override the value with `--set mysql.image.version=not-so-latest`.

I hope it's clearer, if not let me know what part you don't understand, and maybe you can help us to improve the documentation?

**Comment by drozzy** [comment]
It is clear now! Thank you 👍
