### ISSUE TITLE
compose 3.7?

### ISSUE THREAD

**Issue by drozzy** [docker/app#344]
Running this with docker-compose version set to 3.7 I get:

`Error: failed to load Compose file: unsupported Compose file version: 3.7`

Any chance we can get an update? 3.7 has sweet automatic rollback with `rollback_config` [option](https://docs.docker.com/compose/compose-file/#rollback_config).

**Comment by vdemeester** [comment]
@drozzy are you `v0.3.0` ? The next version `v0.4.0` should support it (dependency to `docker/cli` has been bumped and thus support for composeflie `3.7` will be supported :wink:)

**Comment by drozzy** [comment]
Yeah, I'm on 0.3.0.

**Comment by chris-crone** [comment]
[v0.4.0 has been released](https://github.com/docker/app/releases/tag/v0.4.0) so closing this issue.
