### ISSUE TITLE
Allow creating Helm charts not requiring "Compose Kubernetes controller"

### ISSUE THREAD

**Issue by micaelgallego** [docker/app#348]
The project README file, in the [Integration with Helm](https://github.com/docker/app#integrating-with-helm) section, states: 

> Note that this requires the Compose Kubernetes controller available in Docker for Windows and Docker for Mac, and in Docker Enterprise Edition.

It is planned to generate Helm charts not requiring this controller installed in Kubernetes? I suppose it is very difficult to have all docker-compose features available without this "compatibility" controller, but for simple apps defined with a basic subset of docker-compose, this requirement is an important stopper for adoption.

On the other hand, is possible to install "Compose Kubernetes Controller" in your own Kubernetes? I can't find any information searching with Google.

**Comment by chris-crone** [comment]
Hi @micaelgallego. @garethr answered this here: https://github.com/docker/app/issues/239#issuecomment-400213424.

**Comment by jamshid** [comment]
The README no longer mentions Helm. Was functionality dropped? 

Is this project really going forward after the Docker restructuring?
