### ISSUE TITLE
Validate gives bad error msg if file not found

### ISSUE THREAD

**Issue by mikeparker** [docker/app#393]
$ docker-app validate ../examples/hello-world/hello-world.dockerapp

$ docker-app validate ../examples/hello-world/non-existent-file
Error: invalid reference format

Might be nice if it said 'file not found'.

I actually found this by accidentally creating an empty tmp dir in the /examples/ repo, which then causes `TestExamplesAreValid` to fail with the above error message.

**Comment by ulyssessouza** [comment]
Hmmm... Maybe it's in an old version or system difference, but my output is:
```sh
$ docker-app validate ../examples/hello-world/non-existent-file
Error: cannot locate application "../examples/hello-world/non-existent-file" on filesystem
``` 
I'm on:

```
$ docker-app version
Version:      v0.6.0-25-g79f639bd46
Git commit:   79f639bd
Built:        Tue Dec 18 09:15:38 2018
OS/Arch:      linux/amd64
Experimental: off
Renderers:    none
```

```
$ uname -a
Linux ulysses-work 4.18.20-1-MANJARO #1 SMP PREEMPT Wed Nov 21 19:34:18 UTC 2018 x86_64 GNU/Linux
```

**Comment by mikeparker** [comment]
Its quite likely someone fixed this in the meantime.
