### ISSUE TITLE
Using --set with string representing numeric value ending with 0 get truncated

### ISSUE THREAD

**Issue by jhrabi** [docker/app#400]
**Description**

When using --set to replace a value, if the value is in a numeric format ending with 0, the value is being truncated instead of being treated as a string. 

**Steps to reproduce the issue:**
1. Create a file called foo.dockerapp containing the following:
```
version: 0.1.0
name: foo

---
version: "3.6"
services:
  foo:
    image: "foo:${CONTAINER_TAG}"

---
CONTAINER_TAG: 12.59
```
2. docker-app render foo.dockerapp --set CONTAINER_TAG=12.60 

**Describe the results you received:**

```
version: "3.6"
services:
  foo:
    image: foo:12.6
```

**Describe the results you expected:**

```
version: "3.6"
services:
  foo:
    image: foo:12.60
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Quoting the string appears to have no affect. I tried both:

    docker-app render foo.dockerapp --set CONTAINER_TAG="12.60"

and 

    docker-app render foo.dockerapp --set "CONTAINER_TAG=12.60"

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:20:16 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:23:58 2018
  OS/Arch:      linux/amd64
  Experimental: false

```

**Output of `docker-app version`:**

```
Version:      v0.5.0
Git commit:   aef230ad
Built:        Fri Sep 14 11:42:46 2018
OS/Arch:      linux/amd64
Experimental: off
Renderers:    none

```

**Output of `docker info`:**

```
Containers: 177
 Running: 11
 Paused: 0
 Stopped: 166
Images: 3095
Server Version: 18.03.1-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.2.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.26GiB
Name: testserver
ID: 4UV7:LJWO:PRJP:PJWY:YEYA:5RLZ:23XJ:TDFB:3G4L:SST7:5RSJ:UBQU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on AWS

**Comment by mnottale** [comment]
Your quoting fails because the shell is eating up the quotes. Try with `docker-app render foo -s 'CONTAINER_TAG="12.60"'` and it will work.

**Comment by jhrabi** [comment]
Thanks, that does work. Is this a workaround though or is this suppose to be the intended flow?

**Comment by mnottale** [comment]
The value argument to -s is parsed as a YAML value to preserve its type. This is not currently used but might be in the future to allow more advanced substitutions.

**Comment by ijc** [comment]
I believe mnotalle was answering "yes, this is the intended flow" so I'm going to close this. Thanks for your report.
