### ISSUE TITLE
How to access experimental build?

### ISSUE THREAD

**Issue by kinghuang** [docker/app#415]
**Description**

There are several mentions of an “experimental” build of docker-app in many of the issues. I'm unclear on how to access the experimental build. Is it a different version of docker-app to download? Or, do I need to set certain flags/environment variables?

**Steps to reproduce the issue:**

1. Run docker-app.
2. ?
3. Profit.

**Output of `docker-app version`:**

```
Version:      v0.6.0
Git commit:   9f9c6680
Built:        Thu Oct  4 13:30:33 2018
OS/Arch:      darwin/amd64
Experimental: off
Renderers:    none
```

**Comment by silvin-lubecki** [comment]
Hello @kinghuang, thank you for asking!
Experimental mode is only available if you rebuild the binary yourself:
```
$ make EXPERIMENTAL=on bin/docker-app
$ ?
$ ./bin/docker-app inspec profit
```

**Comment by ijc** [comment]
Is this worth a short note in `README.md` and or `BUILDING.md`?
