### ISSUE TITLE
Use .env files to manage environment variables

### ISSUE THREAD

**Issue by allentv** [docker/app#427]
**Description**
Currently `-set` is used to inject environment variables. Docker compose support `.env` files for loading environment variables. Is it possible to inject `.env` files as a flag to support custom values for variables? This would be very useful for testing different configurations by just updating a flag during runtime.

**Comment by silvin-lubecki** [comment]
Hello @allentv , thank you for filling this issue.
`docker-app` can already take a parameters file with the `--parameters-files` flag.
It takes a `YAML` file as input, and you can define and organize your values as a tree:
```
path:
    to:
        my-variable: myvalue
        other-variable: othervalue
```
Then you can use these as variables in the compose file with this syntax: `${path.to.my-variable}`

Does that fit your use case?

**Comment by allentv** [comment]
That definitely fits my use-case. Out of curiosity, are multiple parameter files supported?

**Comment by ulyssessouza** [comment]
@allentv Definitely!
You can achieve that by repeating the flag `--parameters-files` or it's short form `-f` as in:
```sh
$ docker-app render -f params-first.yml -f params-second.yml
```

**Comment by allentv** [comment]
Good stuff. Thanks for getting back to me!
