### ISSUE TITLE
Unable to create a context and test CNAB

### ISSUE THREAD

**Issue by devilmind81** [docker/app#468]
Hi all,
I'm installed docker-app and it is working as expected for the dynamic parameters.
I would like to test the install and upgrade procedure but following the instructions, 
I'm not able to create the context using the command:

`docker context create swarm --description "swarm context" --default-stack-orchestrator=swarm --docker=host=unix:///var/run/docker.sock
`

Seems that the context command isn't available yet.

I'm using a docker version 18.09.2, is the method deprecated? 
How can I reach the same scope in order to test CNAB?

Thanks in advance!

**Comment by garethr** [comment]
Hi @devilmind81. `docker context` is currently only in master for docker, it will be available in the next major release. For the moment we also have it vendored under `docker-app` itself. Try the above with:

```
docker-app context ...
```

We'll fix up the instructions in the README too.

**Comment by devilmind81** [comment]
Thank you! That's worked.
I have used:

docker-app context create swarm --description "swarm context" --default-stack-orchestrator=swarm --docker-host=unix:///var/run/docker.sock

Thanks a lot!

**Comment by silvin-lubecki** [comment]
As this issue has been resolved by @garethr comment, I will close it. @devilmind81 feel free to re-open it if you think it's not the case.
