### ISSUE TITLE
Placeholders in list values become map entries with null values

### ISSUE THREAD

**Issue by dschulten** [docker/app#485]
**Description**

Placeholders in list values become map entries with null values

**Steps to reproduce the issue:**
1. Compose file:
```
    networks:
      - foo-${stage:-dev}
```
2. init and remove the default value -dev from the resulting docker-compose
3. render

**Describe the results you received:**
```
    networks:
      foo-dev: null
```

**Describe the results you expected:**
```
    networks:
      -  foo-dev
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:47:20 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Output of `docker-app version`:**

```
Version:      v0.7.3
Git commit:   332efaa
Built:        Fri Nov 30 15:17:53 2018
OS/Arch:      linux/amd64
Experimental: off
Renderers:    none
```

**Comment by silvin-lubecki** [comment]
Hello @dschulten , thank you for filling this issue !

Of course it's not a pretty result, but the `render` command was mostly made to be pipped to `docker-compose up` or `docker stack deploy`, or to be reviewed by humans before deployment, not to be used or edited by humans.
Also I think that the current behavior produces a valid yaml file and a valid compose file format, and after @zappy-shu dug into the [code](https://github.com/docker/cli/blob/master/cli/compose/types/types.go#L191) it appears it won't be simple to fix this behavior (we would have to patch the golang yaml library).

For these reasons I will close this issue, but feel free to comment on it, or to re-open it if you think our analysis is wrong 👍
