### ISSUE TITLE
Push command should be able to push any CNAB bundle

### ISSUE THREAD

**Issue by silvin-lubecki** [docker/app#526]
**Description**
`docker app push my-bundle/bundle.json --tag my-user/my-app:mytag` does not work. `docker app push` wants a dockerapp, while it doesn't really need it. It should resolve a reference, a bundle or a dockerapp like the other commands.

**Comment by ijc** [comment]
I don't fully follow this one, does "wants a dockerapp" just mean that it expects to find a `foo.dockerapp` somewhere in/around the cwd (despite not really needing it)?

Or do you mean it is expecting something specific to docker app in the `bundle.json`?

**Comment by silvin-lubecki** [comment]
Yes the current implementation expects a dockerapp, but I think it is too restrictive as we rely on cnab to oci which can push any cnab. I think we can remove this constraint while resolving the app name in the code, just by using the resolveBundle function.
