### ISSUE TITLE
Include docker-app plugin with docker image

### ISSUE THREAD

**Issue by kinghuang** [docker/app#532]
**Description**

Can the docker-app 0.8.0 CLI plugin be included with the [docker](https://hub.docker.com/_/docker/) 19.03 image (currently at docker:19.03.0-beta3)?

I previously asked for a docker-app image in #367, similar to the [docker/compose](https://hub.docker.com/r/docker/compose) image. But, with docker-app now functioning as a CLI plugin, it would be preferable to have it as part of the docker image.

**Steps to reproduce the issue:**

1. Run a container with the docker:19.03.0-beta3 image.
2. Attempt to use `docker app` commands.

**Describe the results you received:**

`docker app` commands aren't available. The docker-app CLI plugin is not included with the docker image.

**Describe the results you expected:**

Be able to use `docker app` commands.

**Additional information you deem important (e.g. issue happens only occasionally):**

There is currently no official image with Docker App, either as a plugin or as a standalone command. I need an image for CI jobs that use Docker App.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.0-beta3
 API version:       1.40
 Go version:        go1.12.4
 Git commit:        c55e026
 Built:             Thu Apr 25 02:55:45 2019
 OS/Arch:           linux/amd64
 Experimental:      false

```

**Output of `docker-app version`:**

Docker App is not available in the docker image.

**Output of `docker info`:**

N/A

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by ijc** [comment]
This is a sensible suggestion but I don't think it can be actioned directly here in this repo.

I think this should probably be reported against https://github.com/docker-library/docker which I think is where https://hub.docker.com/_/docker/ comes from.

**Comment by kinghuang** [comment]
Makes sense. I've opened an issue in docker-library/docker#156, and I'll close this one.

**Comment by kinghuang** [comment]
Looks like it's not going to happen on the docker image.
