### ISSUE TITLE
Add bash completion

### ISSUE THREAD

**Issue by chris-crone** [docker/app#54]
https://github.com/spf13/cobra/blob/master/bash_completions.md

**Comment by Dimrok** [comment]
We could add a `docker-app completion` like `kubectl` does?

```
Settings Commands:
  [...]
  completion     Output shell completion code for the specified shell (bash or zsh)
```

It's basically free, thanks to cobra.

**Comment by garethr** [comment]
This commit added a completion command https://github.com/docker/app/commit/900341a8b2312e6a3f5bd9948bb7b45eba12ef5c and this should be in the next release.
