### ISSUE TITLE
Installation version not updated

### ISSUE THREAD

**Issue by nelvadas** [docker/app#547]
curl -fsSL --output "/tmp/docker-app-${OSTYPE}.tar.gz" "https://github.com/docker/app/releases/download/v0.6.0/docker-app-${OSTYPE}.tar.gz"

Last version is 0.8.0

**Comment by chris-crone** [comment]
Hi @nelvadas,

Nice catch! I've put up a PR to fix this: https://github.com/docker/app/pull/548
