### ISSUE TITLE
CLRF issue on Windows

### ISSUE THREAD

**Issue by orosznyet** [docker/app#553]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

The problem is simple, my dockerapp file had *\r\n* new lines on Windows and I've got the following error message:
```Error: malformed single-file application: expected 3 documents, got 1```

I found out that the [SingleFileSeparator](https://github.com/docker/app/blob/9c7217276fce13c468910b8b4f7f2521e3339c73/types/types.go#L17) (as of version v0.8.0) only accepts *\n* style linebreaks which is perfectly fine, although it becomes a problem in the [loader](https://github.com/docker/app/blob/5a3bec9337e5e073cc908be8be2f27bfe856f6e7/loader/loader.go#L24).

**Quick solution**

Simply change the file to LF instead of CLRF and save it.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker-app version`:**

```
Version:               v0.8.0
Git commit:            7eea32b7
Built:                 Tue Jun 11 20:53:26 2019
OS/Arch:               windows/amd64
Experimental:          off
Renderers:             none
Invocation Base Image: docker/cnab-app-base:v0.8.0
```

**Comment by silvin-lubecki** [comment]
Hello @orosznyet , thank you for filling this issue, it is certainly a bug 👍

**Comment by ulyssessouza** [comment]
Fixed by https://github.com/docker/app/pull/561
