### ISSUE TITLE
Issue running make, getting `gotestsum: not found`

### ISSUE THREAD

**Issue by BattleBas** [docker/app#586]
When running the command `make` it fails to run the unit tests and returns the error `gotestsum: not found`. The quick fix is to simply run `go get gotest.tools/gotestsum`, and this could be the right answer but this isn't mentioned in the BUILDING.md and it is automated in the docker.Makefile.

So my question is, should the BUILDING.md be updated to mention this step ? Or should the Makefile be updated to run `git clone -q https://github.com/gotestyourself/gotestsum` like the docker.Makefile does? 

Thanks!

**Steps to reproduce the issue:**
1. Run `make`
2. Get to: `Running unit tests...`

**Describe the results you received:**
`gotestsum: not found`

**Describe the results you expected:**
The unit tests to execute

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Version: 18.09.7
```

**Output of `docker-app version`:**

```
Latest checkout from master
```

**Comment by jcsirot** [comment]
Hi @BattleBas Thank you for opening this ticket. Indeed we are going to update BUILDING.md
