### ISSUE TITLE
User network failure when data-root has been changed

### ISSUE THREAD

**Issue by mvb131988** [docker/app#620]
I'm changing docker data-root(I need to keep volume data in different location) by doing the following steps:

Open up /lib/systemd/system/docker.service

Replace ExecStart=/usr/bin/dockerd -H fd:// $DOCKER_OPTS

with ExecStart=/usr/bin/dockerd --data-root /data/ -H fd:// $DOCKER_OPTS

Restart:

systemctl daemon-reload  systemctl restart docker

Now I'm creating user network docker network create --subnet=172.18.0.0/16 shop-network and launching container docker run -it --net shop-network --ip 172.18.0.12 shopliquibase.

I'm trying to ping external resources(internet) as well as another container started on shop-network and in both cases getting no response.

I've tried to do the same thing on default configuration (without data-root being set) and it works. I've also tried with set data-root on default bridge network and it also works.

Could you give any hint or reference on how could I investigate the problem.

**Comment by rumpl** [comment]
Hey @mvb131988 I'm not sure this issue is related to docker app, I will close it, you should try [moby/moby](https://github.com/moby/moby), if you think however that it's related to docker app feel free to reopen it.
